[options]
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  # User changes
  statusline_unicode_symbols = true 
  vimcompatible = true 
  filemanager = "nerdtree"

[[layers]]
  name = 'core'
  enable_smooth_scrolling = false
[[layers]]
  name = 'ui'
  indentline_char = ''
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
  auto_completion_complete_with_key_sequence_delay = 1
  auto_completion_delay = 500
[[layers]]
  name = 'fzf'
[[layers]]
  name = 'git'
  git_plugin = 'fugitive'
[[layers]]
  name = 'lang#graphql'
[[layers]]
  name = 'lang#html'
[[layers]]
  name = 'lang#javascript'
[[layers]]
  name = 'lang#dockerfile'
[[layers]]
  name = 'lang#markdown'
[[layers]]
  name = 'lang#php'
[[layers]]                                                            
  name = 'lang#rust'
[[layers]]                                                            
  name = 'lang#sh'
[[layers]]
  name = 'lang#typescript'
[[layers]]
  name = 'lang#vue'
[[layers]]
  name = 'lang#vim'

